name: fluttercom
description: A flutter plugin for Intercom.
author: Jon Scalet <jon.scalet@gmail.com>
homepage: https://github.com/j0nscalet
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.fluttercom
        pluginClass: FluttercomPlugin
      ios:
        pluginClass: FluttercomPlugin
